### ISSUE TITLE
Add support for root_endpoint in web.conf

### ISSUE THREAD

**Issue by d3vil-st** [splunk/splunk-ansible#165]
default.yml missing option for root_endpoint, that could be needed if you deploying splunk in kubernetes behind ingress in subpath URL. For example it is not working with this ingress:
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: splunk
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /splunk/
        backend:
          serviceName: master
          servicePort: splunkweb
```
Continuously redirecting from http://server/splunk/ to http://server/en-US/splunk/

**Comment by c3-rockyong** [comment]
you have to put the following in your default.yml:
```
splunk:
  conf:
    web:
      directory: /opt/splunk/etc/system/local/
      content:
        settings:
          root_endpoint: /splunk
```

that will create a custom web.conf that does what you want. took me forever to discover this bit too
