### ISSUE TITLE
Need ability to enable splunktcp-ssl for indexer discovery input

### ISSUE THREAD

**Issue by splunkbot9000** [splunk/splunk-ansible#251]
Like the title says. I have a need to be able to enable splunktcp-ssl instead of regular splunktcp on indexer discovery inputs. Trying to override this after the fact breaks idempotency.

**Comment by nwang92** [comment]
I added this functionality in the develop branch right now. You'll need to regenerate the default.yml and modify this section:
````
splunk:
  s2s:
    enable: True
    port: 9997
    ssl: False
    cert:
    password:
    ca:
```

We just released the 8.0.1 Splunk images, so this feature will likely be available in the next release.
