### ISSUE TITLE
PID 1 not showing systemd on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by jacobappleton-orbis** [splunk/splunk-ansible#313]
In [enable_service.yml](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/enable_service.yml) we inspect the output of `ps 1` and test it to find the string `"systemd"` to identify if we're running systemd or init.

```
- name: "Retrieve PID 1 process information (Linux)"
  command: "ps 1"
  register: pid1
  when:  ansible_system is match("Linux")
```

```
- name: "Enable service via boot-start - Linux (systemd)"
  become: yes
  become_user: "{{ privileged_user }}"
  command: "{{ splunk.exec }} enable boot-start -systemd-managed 1 -user {{ splunk.user }} --accept-license --answer-yes --no-prompt"
  when:
    - ansible_system is match("Linux")
    - pid1.stdout.find("systemd") != -1
    - installed_splunk_version[0] is version("7.2.2", ">=")

- name: "Enable service via boot-start - Linux (init)"
  become: yes
  become_user: "{{ privileged_user }}"
  command: "{{ splunk.exec }} enable boot-start -user {{ splunk.user }} --accept-license --answer-yes --no-prompt"
  when: ansible_system is match("Linux") and pid1.stdout.find('systemd') == -1
```

On Ubuntu 18.04.3 LTS, `ps 1` returns:
```
$ ps 1
PID TTY      STAT   TIME COMMAND
  1 ?        Ss     0:03 /sbin/init
```
where /sbin/init is a symlink to `/lib/systemd/systemd`

```
$ file /sbin/init
/sbin/init: symbolic link to /lib/systemd/systemd
```

From SuperUser I found this potential solution: [https://superuser.com/a/1183819](https://superuser.com/a/1183819).
