### ISSUE TITLE
Set license to slave ignore errors

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#36]
It would be really awesome if https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/set_as_license_slave.yml#L7 has `ignore_errors: yes`. In local setups and lower environments we might not have a real license configured. Currently I'm using the post install hook added on #31 to bypass the standard slave set like so
```
    ---
    - name: CUSTOM Set node as license slave
      command: "{{ splunk.exec }} edit licenser-localslave -master_uri https://license-master:{{ splunk.svc_port }} -auth 'admin:{{ splunk.password }}'"
      register: lic_slave
      until: lic_slave.rc == 0
      retries: "{{ retry_num }}"
      delay: 3
      ignore_errors: yes
      notify:
        - Restart the splunkd service
```

Note that I'm hardcoding the license-master hostname instead of applying though the environment variable. By not setting `SPLUNK_LICENSE_MASTER_URL`, the task included in this repo isn't being run.
