### ISSUE TITLE
splunk_deployment_server role attempts to disable non-existent apps

### ISSUE THREAD

**Issue by scalatar** [splunk/splunk-ansible#413]
Maybe I'm missing something but I can't seem to prevent the splunk_deployment_server role from failing during build. 

In splunk_deployment_server/tasks/main.yml the order of tasks is as follows:
1) Enable forwarding (no issues there):
`- include_tasks: ../../../roles/splunk_common/tasks/enable_forwarding.yml`
2) Create deployment apps:
```
- include_tasks: create_deployment_apps.yml
  when:
    - splunk.apps_location
```
3) **During create deployment** > apps are installed, to `splunk.apps_path.default`:
```
- include_tasks: install_deployment_apps.yml
  vars:
    app_url: "{{ item }}"
  loop: "{{ splunk.apps_location }}"
```

4) **During create deployment** > Installed apps are enumerated into `installed_apps`, which includes the apps we just installed:
`- include_tasks: ../../../roles/splunk_common/tasks/find_installed_apps.yml`

5) **During create deployment** > Apps are **copied** from `splunk.apps_path.default` to `splunk.apps_path.deployment` using `installed_apps` variable list:
```
# TODO: Might be better to use synchronize here, but we'll need rsync installed
- name: Copy installed apps to deployment-apps
  command: "cp -R {{ splunk.app_paths.default }}/{{ item }} {{ splunk.app_paths.deployment }}"
  register: copy_apps
  changed_when: copy_apps.rc == 0
  failed_when: copy_apps.rc != 0
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
```

6) **During create deployment** > Installed apps are removed

```
- name: Remove installed apps
  file:
    path: "{{ splunk.app_paths.default }}/{{ item }}"
    state: absent
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
  notify:
    - Restart the splunkd service

- name: Flush restart handlers
  meta: flush_handlers
```

7) Now we're all done create deployment and we're back in splunk_deployment_server main and we execute `disable_installed_apps`, which uses the old updated `installed_apps` variable containing the apps we just removed in step 6 above:
```
- include_tasks: ../../../roles/splunk_common/tasks/disable_installed_apps.yml
  when:
    - splunk.apps_location
```
and the problem I think is here, where the already built `installed_apps` is being used
```
- include_tasks: find_installed_apps.yml
  when: not installed_apps

- name: Disable installed_apps
  command: "{{ splunk.exec }} disable app {{ item }} -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
  when: installed_apps
```

Again I might be missing something but I think possibly the disable_installed_apps task can be removed from the splunk_deployment_server role?
