### ISSUE TITLE
set_as_hec_receiver.yml runs without a check for hec

### ISSUE THREAD

**Issue by scalatar** [splunk/splunk-ansible#423]
It's possible I'm misunderstanding the intention of the  `set_as_hec_receiver.yml` task. But I think there should be a check to see if splunk.hec is set.

For instance in the splunk_indexer role this task is run without any check:
```
---
- include_tasks: ../../../roles/splunk_common/tasks/set_as_hec_receiver.yml

- include_tasks: indexer_clustering.yml
  when: splunk_indexer_cluster | bool
```

Which might be ok but the task `set_as_hec_receiver.yml` run this every time:
```
- name: Setup global HEC
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/services/data/inputs/http/http"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body:
      disabled: "{% if ('hec' in splunk and 'enable' in splunk.hec and splunk.hec.enable | bool) or ('hec_disabled' in splunk and not splunk.hec_disabled | bool) %}0{% else %}1{% endif %}"
      enableSSL: "{% if ('hec' in splunk and 'ssl' in splunk.hec and splunk.hec.ssl | bool) or ('hec_enableSSL' in splunk and splunk.hec_enableSSL | bool) %}1{% else %}0{% endif %}"
      port: "{% if 'hec' in splunk and 'port' in splunk.hec and splunk.hec.port %}{{ splunk.hec.port }}{% elif 'hec_port' in splunk and splunk.hec_port %}{{ splunk.hec_port }}{% else %}8088{% endif %}"
    body_format: "form-urlencoded"
    status_code: 200
    timeout: 10
  no_log: "{{ hide_password }}"
```

It would be good if hec setup was skipped when hec is disabled or undefined. I think adding this:
`when: ('hec' in splunk and splunk.hec.enable and 'token' in splunk.hec) or ('hec_token' in splunk)`

to: 

- `Setup global HEC`
- `Remove existing HEC token`

Would ensure that this task was skipped when hec wasn't defined.

**Comment by nwang92** [comment]
The `default.yml` you provide to the container is read and merged over one that's baked into splunk-ansible here: https://github.com/splunk/splunk-ansible/blob/develop/inventory/splunk_defaults_linux.yml. So if you neglect to pass in `splunk.hec` or `splunk.hec.*`, this ensures that every stanza is fully defined by falling back to some safe defaults.

**Comment by scalatar** [comment]
Right, that makes sense and I guess I was misreading the intention of `Setup global HEC`. When I pass this:

```
splunk: 
        hec:
                enable: False
                port: 8088
                ssl: True
                token:
```
I guess I was expecting `Setup global HEC` to not run at all, versus passing the correct value to `disabled:`. But for multiple runs of this task on already configured instances I can understand why this is being done. 

The problem I am seeing is that during build, `Setup global HEC` is failing the during cluster build. I found that if I forced `Setup global HEC` to be skipped during the build everything would complete. 

This is probably more of an issue with the lab environment I'm running than the logical flow of the code although having a way to limit the number of calls to Splunk during build would be nice. Maybe a retry would be good in `Setup global HEC` versus try once and fail?
