### ISSUE TITLE
ability to specify config files with the same name in /tmp/defaults/default.yml

### ISSUE THREAD

**Issue by j4ys0n** [splunk/splunk-ansible#426]
it would be handy to be able to specify files of the same name in different paths using the `/tmp/defaults/default.yml` file. 

like:
```yaml
splunk:
    conf:
        inputs:
            directory: /opt/splunk/etc/apps/search/local
            content:
                "udp://8125":
                    connection_host: ip
                    index: docker_metrics
                    sourcetype: statsd
        inputs:
            directory: /opt/splunk/etc/apps/mongodb/local
            content:
                "mongo_admin://top":
                    index: mongodb
                    disabled: 1
                    interval: 15
                    commands: top ping
                    server: mongodb
                    port: 27017
                    username: admin
                    password: admin
```
currently only the last specification is written because it's a duplicate key.

a way to input a list would be awesome!
