### ISSUE TITLE
Deployment Server deployment times out when reloading

### ISSUE THREAD

**Issue by auzroz** [splunk/splunk-ansible#440]
We have a pre-task that loads apps from our Git repo into deployment-apps, traditionally on bare metal, we need to add a "-timeout 200" to the reload command in order for the DS reload process to succeed. In splunk-docker/8.0.3-debian, the reload task times out the max number of retries and then ignores the failure. 

Workaround is to programmatically rewrite the task to add this argument. Recommending add a variable in order to account for large Deployment Server environments.

```
- name: "extend timeout in deployment server deployment playbook"
  become: yes
  become_user: root
  lineinfile:
    path: /opt/ansible/roles/splunk_deployment_server/tasks/main.yml
    regexp: "^  command:"
    line: '  command: "{{ splunk.exec }} reload deploy-server -auth {{ splunk.admin_user }}:{{ splunk.password }} -timeout 600"'
```
