### ISSUE TITLE
[GUIDANCE] SHC-Deployer SPLUNK_APPS_URL

### ISSUE THREAD

**Issue by amp4045** [splunk/splunk-ansible#562]
Hey all, this isn't necessarily a bug.. but I'm looking for some guidance.

I'm struggling to setup the deployer whenever I have the SPLUNK_APPS_URL set.
Unfortunately it appears I loop on "Wait for SHC to be ready", until all attempts fail. 

The error I see back is there's not enough peers.

That being said, the rest of my cluster stands up fine:
1 License-master (Deployment)
1 Deployment-Server (Deployment)
2 splunk_search_head (StatefulSet)
1 splunk_search_head_captain (Deployment)
1 cluster_master (Deployment)
3 indexer pods (StatefulSet)

I can see through the splunk gui that everything is wired up correctly. The status is green, and looking under advanced settings shows all of my pods...

From one of the sh-members I can 'splunk show shcluster-status' and see two search heads + 1 captain have clustered, and a captain has been decided. I see the index peers are setup & clustered correctly (show cluster-status from the CM).

What else am I missing? I've been stuck on this for a day or two now. 

Thank you!

**Comment by amp4045** [comment]
Thought I should mention. 
I'm attempting to just deploy a single app for now via SPLUNK_APP_URL, it's a .tgz persisted on the volume under /tmp/myapp.tgz

Without passing the var, the deployer standsup fine otherwise (but obviously doesn't deploy anything)

**Comment by nwang92** [comment]
I don't believe the apps plays get invoked on the deployer until after the SHC is formed. Have you set the SHC pass4SymmKey to be common between all SHC members and the deployer? Are you using persistent volumes? Could you maybe share the `default.yml` you're using?

**Comment by nwang92** [comment]
Also wondering if the you're mounting the app in `/tmp/app.tgz` might be interfering with the location of the `/tmp/defaults/default.yml` the deployer is reading from - I would check that both files exist in the deployer.

**Comment by amp4045** [comment]
@nwang92 Thanks for getting back to me so soon! Sorry I've disappeared for the weekend.

Unfortunately I don't have a way to share the default.yml file - we're in an environment we cannot access the internet from that machine. The default.yml was created before I jumped in to assist this deployment. 

I jumped on the search-head-0, search-head-1, search-head-captain, and search-head-deployer - under [general] in /opt/splunk/etc/system/local/server.conf

It looks like there are different hashes. Could that be my issue?
For what it's worth, our default.yml almost looks entirely like:

https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md

**Comment by amp4045** [comment]
As far as the SHC section: Ours looks like:

shc:
    enable: true
    label: shc_label
    replication_factor: 3
    replication_port: 9887
    secret: <someRandomStringValueHere>

**Comment by amp4045** [comment]
> 
> 
> Also wondering if the you're mounting the app in `/tmp/app.tgz` might be interfering with the location of the `/tmp/defaults/default.yml` the deployer is reading from - I would check that both files exist in the deployer.

We're putting the app(s) on a persistent volume and mounting to /tmp/apps on the splunk_search_head_deployer. As of right now, multiple apps get there, (.tgz files) but we're only providing a single app url for testing purposes.

**Comment by amp4045** [comment]
Here's our default.yml:

```
---
ansible_post_tasks: null
ansible_pre_tasks: null
cert_prefix: http
config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: false
  max_delay: 60
  max_retries: 3
  max_timeout: 1200
hide_password: false
shc_bootstrap_delay: 30
retry_num: 100
splunk:
  admin_user: admin
  allow_upgrade: true
  app_paths:
    default: /opt/splunk/etc/apps
    deployment: /opt/splunk/etc/deployment-apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  enable_service: false
  disable_popups: true
  exec: /opt/splunk/bin/splunk
  group: splunk
  hec_disabled: 0
  hec_enabledSSL: 1
  hec_port: 8088
  hec_token: - some token here- 
  home: /opt/splunk
  http_enableSSL: 0
  http_enableSSL_cert: null
  http_enableSSL_privKey: null
  http_enableSSL_privKey_password: null
  http_port: 8000
  idxc:
    enable: true
    label: idxc_label
    replication_factor: 3
    replication_port: 9887
    search_factor: 3
    secret: -SomeSecretHere-
  ignore_license: false
  license_download_dest: /tmp/license/splunk.lic
  opt: /opt
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  root_endpoint: /splunk
  s2s_enable: true
  s2s_port: 9997
  search_head_captain_url: null
  shc:
    enable: true
    label: shc_label
    replication_factor: 3
    replication_port: 9887
    secret: -ShcSecretHere-
  smartstore: null
  svc_port: 8089
  tar_dir: splunk
  user: splunk
  wildcard_license: false
splunk_home_ownership_enforcement: true
```

**Comment by nwang92** [comment]
> It looks like there are different hashes. Could that be my issue?

I don't believe so; the hash that would matter here is the one under `[shclustering]` stanza, and it may appear different because it's hashed. You can decrypt this hashed value to see the plaintext value to make sure it's correct via:
```
/opt/splunk/bin/splunk show-decrypted --value 'hash'
```

This would be good to confirm on all SHC members (SH + deployer) agree on the same pass4SymmKey.

When you loop + fail on the "Wait for SHC to be ready" task, is there an error message at the end? Are you using persistent volumes for the etc/var directories of Splunk? Would it be feasible to see if this works without persistent volumes (by using emptyDirs)?

Also, do you have the sample k8s manifest file you're using for the deployer? I can try to replicate what you're running in my own env if you can show me how the deployer/sh's are constructed.

**Comment by amp4045** [comment]
@nwang92 Let me see what I can get you later today/tomorrow. Tomorrow I will also decrypt and confirm the hash value under the [shclustering] stanza

**Comment by amp4045** [comment]
@nwang92 Confirmed all decrypted plain-text values are the same across the 2 search-heads, 1 sh-captain, and 1 deployer.
Once again, I see (from the captain) running ./splunk show shcluster-status -auth <user>:<pass> that the captain & search heads have clustered. Min_peer_flags set to 1.

The Deployer has failed waiting for SHC to be ready again with an error of "SHC failure, setup not complete. Insufficient number of peers online".

Here's the task for the deployer;

```
---
- name: deploy search-head-deployer
  k8s:
    state: "{{ splunk_state }}"
    namespace: "{{ namespace }}"
    api_version: apps/v1
    kind: Deployment
    definition:
      metadata:
        labels:
          app: splunk
          role: search-head-deployer
       name: splunk-search-head-deployer
       spec:
          replicas: 1
          serviceName: search-head-deployer
          selector:
             matchlabels:
               app: splunk
          template:
            metadata:
              labels:
                app: splunk
                role: search-head-deployer 
              spec: 
                dnsPolicy: ClusterFirst
                dnsConfig:
                   searches:
                       - "search-head.{{namespace}}.svc.cluster.local"
                hostname: search-head-deployer
                containers:
                  - image: "{{default_image_splunk}}"
                     imagePullPolicy: always
                     name: search-head-deployer
                     env:
                        - name: SPLUNK_ROLE
                           value: splunk_deployer
                        - name: SPLUNK_START_ARGS
                           value: --accept-license
                        - name: SPLUNK_LICENSE_MASTER_URL
                           value: license-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
                           value: search-head-captain.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_CLUSTER_MASTER_URL
                           value: cluster-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_INDEXER_URL
                           value: "{% for n in range(0, indexer_replicas) %}splunk-indexer-cluster-{{n}}{%- if not loop.last%},{% endif %}{% endfor %}"
                        - name: SPLUNK_SEARCH_HEAD_URL
                           value: "{% for n in range(0, search_head_replicas -1) %}splunk-search-head-{{n}},{% endfor %}search-head-captain/{{namespace}}.svc.cluster.local"
                       - name: SPLUNK_DEPLOYER_URL
                           value: search-head-deployer.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_DEPLOYMENT_SERVER
                           value: deployment-server.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_APPS_URL
                           value: /tmp/apps/myAppHere.tgz
                       - name: SPLUNK_PASSWORD
                           valueFrom:
                             secretKeyRef:
                              key: SPLUNK_PASSWORD
                              name: splunk
                       ports:
                         - containerPort: 8000
                           name: http
                         - containerPort: 8443
                           name: https
                         - containerPort: 8088
                           name: hec
                         - containerPort: 8089
                           name: svc 
                         - containerPort: 9887
                           name: replication
                         - containerPort: 9997
                           name: s2s
                      volumeMounts:
                         - name: defaults
                           mountPath: /tmp/defaults/
                         - name: splunk-search-head-deployer-config
                           mountPath: /tmp/apps
                       volumes:
                         - name: splunk-search-head-deployer-config
                           persistentVolumeClaim:
                             claimName: splunk-search-head-deployer-config  
                         - name: defaults
                           configMap:
                             defaultMode: 511
                             name: splunk
                
               

                
```

**Comment by amp4045** [comment]
here is the Search-Head manifest (not captain)

```
---
- name: deploy search-head-deployer
  k8s:
    state: "{{ splunk_state }}"
    namespace: "{{ namespace }}"
    api_version: apps/v1
    kind: StatefulSet
    definition:
      metadata:
        labels:
          app: splunk
          role: search-head
       name: splunk-search-head
       spec:
          replicas: 2
          serviceName: search-head
          selector:
             matchlabels:
               app: splunk
          template:
            metadata:
              labels:
                app: splunk
                role: search-head
              spec: 
                dnsPolicy: ClusterFirst
                dnsConfig:
                   searches:
                       - "search-head.{{namespace}}.svc.cluster.local"
                hostname: search-head-deployer
                containers:
                  - image: "{{default_image_splunk}}"
                     imagePullPolicy: always
                     name: search-head
                     env:
                        - name: SPLUNK_ROLE
                           value: splunk_search_head
                        - name: SPLUNK_START_ARGS
                           value: --accept-license
                        - name: SPLUNK_LICENSE_MASTER_URL
                           value: license-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
                           value: search-head-captain.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_CLUSTER_MASTER_URL
                           value: cluster-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_INDEXER_URL
                           value: "{% for n in range(0, indexer_replicas) %}splunk-indexer-cluster-{{n}}{%- if not loop.last%},{% endif %}{% endfor %}"
                        - name: SPLUNK_SEARCH_HEAD_URL
                           value: "{% for n in range(0, search_head_replicas -1) %}splunk-search-head-{{n}},{% endfor %}search-head-captain/{{namespace}}.svc.cluster.local"
                       - name: SPLUNK_DEPLOYER_URL
                           value: search-head-deployer.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_DEPLOYMENT_SERVER
                           value: deployment-server.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_PASSWORD
                           valueFrom:
                             secretKeyRef:
                              key: SPLUNK_PASSWORD
                              name: splunk
                       ports:
                         - containerPort: 8000
                           name: http
                         - containerPort: 8443
                           name: https
                         - containerPort: 8088
                           name: hec
                         - containerPort: 8089
                           name: svc 
                         - containerPort: 9887
                           name: replication
                         - containerPort: 9997
                           name: s2s
                      volumeMounts:
                         - name: defaults
                           mountPath: /tmp/defaults/
                       volumes:
                         - name: defaults
                           configMap:
                             defaultMode: 511
                             name: splunk
```

**Comment by amp4045** [comment]
Here's the captain's manifest:

```
---
- name: deploy search-head-captain
  k8s:
    state: "{{ splunk_state }}"
    namespace: "{{ namespace }}"
    api_version: apps/v1
    kind: Deployment
    definition:
      metadata:
        labels:
          app: splunk
          role: search-head-captain
       name: splunk-search-head-captain
       spec:
          replicas: 1
          serviceName: search-head-captain
          selector:
             matchlabels:
               app: splunk
          template:
            metadata:
              labels:
                app: splunk
                role: search-head-captain
              spec: 
                dnsPolicy: ClusterFirst
                dnsConfig:
                   searches:
                       - "search-head.{{namespace}}.svc.cluster.local"
                hostname: search-head-captain
                containers:
                  - image: "{{default_image_splunk}}"
                     imagePullPolicy: always
                     name: search-head-deployer
                     env:
                        - name: SPLUNK_ROLE
                           value: splunk_search_head_captain
                        - name: SPLUNK_START_ARGS
                           value: --accept-license
                        - name: SPLUNK_LICENSE_MASTER_URL
                           value: license-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
                           value: search-head-captain.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_CLUSTER_MASTER_URL
                           value: cluster-master.{{namespace}}.svc.cluster.local
                        - name: SPLUNK_INDEXER_URL
                           value: "{% for n in range(0, indexer_replicas) %}splunk-indexer-cluster-{{n}}{%- if not loop.last%},{% endif %}{% endfor %}"
                        - name: SPLUNK_SEARCH_HEAD_URL
                           value: "{% for n in range(0, search_head_replicas -1) %}splunk-search-head-{{n}},{% endfor %}search-head-captain/{{namespace}}.svc.cluster.local"
                       - name: SPLUNK_DEPLOYER_URL
                           value: search-head-deployer.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_DEPLOYMENT_SERVER
                           value: deployment-server.{{namespace}}.svc.cluster.local
                       - name: SPLUNK_PASSWORD
                           valueFrom:
                             secretKeyRef:
                              key: SPLUNK_PASSWORD
                              name: splunk
                       ports:
                         - containerPort: 8000
                           name: http
                         - containerPort: 8443
                           name: https
                         - containerPort: 8088
                           name: hec
                         - containerPort: 8089
                           name: svc 
                         - containerPort: 9887
                           name: replication
                         - containerPort: 9997
                           name: s2s
                      volumeMounts:
                         - name: defaults
                           mountPath: /tmp/defaults/
                       volumes:
                         - name: defaults
                           configMap:
                             defaultMode: 511
                             name: splunk
                
```
