### ISSUE TITLE
Support for Podman Rootless containers broke

### ISSUE THREAD

**Issue by PrymalInstynct** [splunk/splunk-ansible#607]
## Issue
Between hub.docker.com container versions
- splunk/splunk:8.0.7 and splunk/splunk 8.0.8
OR
- splunk/splunk:8.1.1 and splunk/splunk 8.1.2

The ability to run the container via rootless podman execution stopped working.

It appears that the failure is being caused by the merge of `Feature/declarative password` #517
### Expected Outcome
Splunk container will start running as a rootless user

#### Ansible playbook
```
- hosts: localhost
  become: yes
  tasks:

  - name: "Create Rootless Container Users"
    user:
      name: "{{ item.name }}"
      comment: "{{ item.comment }}"
      uid: "{{ item.uid }}"
    with_items:
      - { name: 'splunkers', comment: 'Splunk Server', uid: '5008' }
  
  - name: "COPY | Setup .bashrc for Rootless Container Users"
    copy:
      src: '.bashrc'
      dest: "/home/{{ item }}"
    with_items:
      - splunkers
  
  - name: "Create ./ansible/tmp diretory for Splunk User"
    file:
      path: /home/splunkers/.ansible/tmp
      recurse: yes
      owner: splunkers
      group: splunkers
      mode: '0770'
  
  - name: "Check if Lingering is enabled for Splunk User"
    stat:
      path: "/var/lib/systemd/linger/splunk"
    register: splunk_lingering
    changed_when: no
  
  - name: "Enabled Lingering for Splunk User"
    command: loginctl enable-linger splunk
    when: not splunk_lingering.stat.exists
  
  - name: "Pull Image for Splunk"
    become: yes
    become_user: splunkers
    podman_image:
      name: splunk/splunk
      tag: '8.0.8'
      state: present
  
  - name: "Add Firewalld Rule for Splunk Container"
    firewalld:
      zone: public
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    with_items:
      - 8000/tcp
      - 8089/tcp
      - 9997/tcp
  
  - name: "Create Volume for Splunk Container"
    become: yes
    become_user: splunkers
    podman_volume:
      name: "{{ item }}"
      state: present
    with_items:
      - splunk_etc
      - splunk_var
  
  - name: "Create & Start Splunk Container"
    become: yes
    become_user: splunkers
    podman_container:
      name: splunk
      image: splunk/splunk:8.0.8
      state: started
      publish:
      - 8000:8000/tcp
      - 8089:8089/tcp
      - 9997:9997/tcp
      env:
        SPLUNK_START_ARGS: "--accept-license"
        SPLUNK_PASSWORD: "changeme"
      volumes:
        - splunk_etc:/opt/splunk/etc
        - splunk_var:/opt/splunk/var

```
### Failure Output
```
TASK [splunk_common : Hash the password] ***************************************
changed: [localhost]
Tuesday 02 March 2021  12:22:08 +0000 (0:00:01.849)       0:00:25.813 ********* 

TASK [splunk_common : Generate user-seed.conf (Linux)] *************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpj8p8k_jauser-seed.conf'
failed: [localhost] (item=USERNAME) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "opt": "USERNAME",
        "val": "admin"
    },
    "warnings": [
        "Module remote_tmp /home/splunk/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually"
    ]
}

MSG:

Failed to replace file: /home/splunk/.ansible/tmp/ansible-moduletmp-1614687729.543946-8smr32ex/tmplgo5eysh to /opt/splunk/etc/system/local/user-seed.conf: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpj8p8k_jauser-seed.conf'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpwvrotvn9user-seed.conf'
failed: [localhost] (item=HASHED_PASSWORD) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "opt": "HASHED_PASSWORD",
        "val": "$6$HQ6sGlWhHM/8bB6R$y0/oFinQzlyOc0EhadG6vXFuPDQEVJUlPSg8b8iS1CYc54aa4HxsYQoQLBjvr74vK4Bj1jPCoizIrSzv1qLjg."
    }
}

MSG:

Failed to replace file: /home/splunk/.ansible/tmp/ansible-moduletmp-1614687729.9419022-rnr489a6/tmpldq0t8vk to /opt/splunk/etc/system/local/user-seed.conf: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpwvrotvn9user-seed.conf'
```

### OS
```
Red Hat Enterprise Linux release 8.3 (Ootpa)
```
### Ansible Version
```
ansible 2.9.17
```
### Podman Version
```
podman version 2.2.1
```
### Containers.podman collection version
```
containers.podman v1.4.3
```

**Comment by nwang92** [comment]
While I procure an instance to install/run podman, do you know if this bug also occurs for a root-enabled podman user? Theoretically what happens in the container shouldn't depend on whether or not the container engine is running as root or without, correct?

**Comment by PrymalInstynct** [comment]
I should have thought to include the fact that this does not impact the container when running it as root. That is the first thing I check whenever running into an issue with a container executing rootless.

The idea is that there is no difference between running a rootful and rootless container but in reality there are limitations. I just cannot pin point what the cause might be in this case though.

**Comment by PrymalInstynct** [comment]
I pulled the latest develop branch for testing and am still seeing the same issue.

The error makes me think its a permissions issue to /opt/splunk/etc/system/local

So I even tested making a task prior to Generate User-seed.conf that opens up the permissions to /opt/splunk/etc/ and down but that didn't solve the problem.
```
TASK [splunk_common : Generate user-seed.conf (Linux)] *****************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpiosq750cuser-seed.conf'
failed: [localhost] (item=USERNAME) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "opt": "USERNAME",
        "val": "admin"
    },
    "warnings": [
        "Module remote_tmp /root/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually"
    ]
}

MSG:

Failed to replace file: /root/.ansible/tmp/ansible-moduletmp-1618941104.062952-p4pn5odj/tmp_7bh4vxi to /opt/splunk/etc/system/local/user-seed.conf: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpiosq750cuser-seed.conf'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpr1_olp27user-seed.conf'
failed: [localhost] (item=HASHED_PASSWORD) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "opt": "HASHED_PASSWORD",
        "val": "$6$5.aEnRbA8cBUhLLR$HE2uAj.JXtaG9sc2/o0ew0PIwqah0/c/jimUm1.bcTSVu0o8fAlyScSDaMt4pyjZJN5TWeLaGjm8h4MxKjdJG/"
    }
}

MSG:

Failed to replace file: /root/.ansible/tmp/ansible-moduletmp-1618941104.235529-97kopyvb/tmp53yr7o67 to /opt/splunk/etc/system/local/user-seed.conf: [Errno 13] Permission denied: b'/opt/splunk/etc/system/local/.ansible_tmpr1_olp27user-seed.conf'
```

**Comment by PrymalInstynct** [comment]
I am starting to make some headway in understanding the issue.

if I create the container like this:
```
podman run -p 8000:8000 \
    -e "SPLUNK_PASSWORD=changeme" \
    -e "SPLUNK_START_ARGS=--accept-license" \
    -it --name so1 splunk/splunk:latest
```
I then exec into it while the ansible runs to start everything up I can execute this

### Command
```
watch -n0.1 sudo ls -lahZ /opt/splunk/etc/system/local
```
The folder has an SELinux Context of `system_u:object_r:container_file_t:s0`

### Output:
```
[ansible@019c495260a1 splunk]$ watch -n0.1 sudo ls -lahZ /opt/splunk/etc/system/local
drwxr-x---. 2 splunk splunk system_u:object_r:container_file_t:s0  20 Apr 21 09:30 .
drwxr-x---. 9 splunk splunk system_u:object_r:container_file_t:s0 104 Mar  9 17:09 ..
-r--r-----. 1 splunk splunk system_u:object_r:container_file_t:s0 265 Mar  9 16:45 README
```

However if I start the container with SELinux Contexts disabled
```
podman run -p 8000:8000 \
    -e "SPLUNK_PASSWORD=changeme" \
    -e "SPLUNK_START_ARGS=--accept-license" \
    --security-opt label=disable \
    -it --name so1 splunk/splunk:latest
```
Then exec in and run the same command

### Command
```
watch -n0.1 sudo ls -lahZ /opt/splunk/etc/system/local
```
### **The container starts without issue**

### Output
```
drwxr-x---. 2 splunk splunk unconfined_u:object_r:container_file_t:s0 102 Apr 21 09:38 .
drwxr-x---. 9 splunk splunk unconfined_u:object_r:container_file_t:s0 104 Mar  9 17:09 ..
-r--r-----. 1 splunk splunk unconfined_u:object_r:container_file_t:s0 265 Mar  9 16:45 README
-rw-r-----. 1 splunk splunk system_u:object_r:fusefs_t:s0              33 Apr 21 09:38 inputs.conf
-rw-------. 1 splunk splunk unconfined_u:object_r:container_file_t:s0  60 Apr 21 09:38 migration.conf
-rw-------. 1 splunk splunk unconfined_u:object_r:container_file_t:s0  36 Apr 21 09:38 server.conf
-rw-r-----. 1 splunk splunk system_u:object_r:fusefs_t:s0             155 Apr 21 09:38 user-seed.conf
```

So I thought to myself what if I set the SELinux Context of the file as a part of task like this
```
  - name: "Generate user-seed.conf (Linux)"
    ini_file:
      owner: "{{ splunk.user }}"
      group: "{{ splunk.group }}"
      seuser: system_u
      serole: object_r
      setype: container_file_t
      dest: "{{ splunk.home }}/etc/system/local/user-seed.conf"
      section: user_info
      option: "{{ item.opt }}"
      value: "{{ item.val }}"
    with_items:
      - { opt: 'USERNAME', val: '{{ splunk.admin_user }}' }
      - { opt: 'HASHED_PASSWORD', val: '{{ hashed_pwd.stdout }}' }
    loop_control:
      label: "{{ item.opt }}"
    when: ansible_system is match("Linux")
    become: yes
    become_user: "{{ splunk.user }}"
    no_log: "{{ hide_password }}"
```
But that didnt work, I got the same result as the originally reported issue.
