### ISSUE TITLE
Unable to pass config to inputs.conf

### ISSUE THREAD

**Issue by gingerwizard** [splunk/splunk-ansible#653]
My understanding based on the spec is that i should be able to pass contents to merged into /opt/splunk/etc/system/local/inputs.yml via default.yml. How this should be provided? The contents of the file are in ini format but this file is yml.

For example the following results in a panic..

defaut.yml
```
splunk:
  conf:
    - key: inputs
      value:
        directory: /opt/splunk/etc/system/local
        content: |
          [splunktcp://9997]
          disabled = 0

          [metrics_sai]
          disabled = 0
          index = em_metrics
          indexes = em_metrics
          sourcetype = em_metrics
          token = 74a4c23a-8911-422c-85dd-6f8a24d1eb72
```

```
TASK [splunk_common : include_tasks] *******************************************
fatal: [localhost]: FAILED! => {}

MSG:

with_dict expects a dict

PLAY RECAP *********************************************************************
localhost                  : ok=41   changed=1    unreachable=0    failed=1    skipped=48   rescued=0    ignored=0   
```

**Comment by gingerwizard** [comment]
for anyone else, convert entirely to yaml

```
splunk:
  conf:
    - key: inputs
      value:
        directory: /opt/splunk/etc/system/local
        content:
          metrics_sai:
            disabled: "0"
            index: "em_metrics"
            indexes: "em_metrics"
            sourcetype: "em_metrics"
            token: "74a4c23a-8911-422c-85dd-6f8a24d1eb72"
```
