### ISSUE TITLE
How to configure etc/system/local on SearchHeads instead of SearchHeadDeployer

### ISSUE THREAD

**Issue by BGrasnick** [splunk/splunk-ansible#673]
Hey all, 

I am using the splunk-operator and I am trying to change some settings in etc/system/local on the SearchHeads but my approach only applies the change on the SearchHeadDeployer...

My config for the SearchHeadCluster contains the following:

```yaml
spec:
  defaults: |-
      splunk:
        conf:
          web:
            content:
              settings:
                splunkdConnectionTimeout: 1800
```

How can I deploy this config in etc/system/local/web.conf on the SearchHeads instead of the SearchHeadDeployer?
