### ISSUE TITLE
Migrate to WiredTiger

### ISSUE THREAD

**Issue by jynolen** [splunk/splunk-ansible#679]
Related to splunk/docker-splunk#540

It might be necessary to add a new task to be able to configure the storageEngine entry in `[kvstore]` section of `server.conf`

**Comment by jenipherc** [comment]
There is the "conf:" key in default.yml that you can utilize in the mean time.
https://splunk.github.io/splunk-ansible/advanced/default.yml.spec.html#spec
See "Configuration files" section.

An example of configuring what you were asking would look like this.

```
splunk:
   conf:
      - key: server
        value:
            directory: /opt/splunk/etc/system/local
            content:
                 kvstore:
                     storageEngine: wiredTiger
 ```
This format is applicable for recent version of "splunk-ansible" per document mentioned above.
