### ISSUE TITLE
How it is possible to use explicit site_replication_factor?

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-ansible#744]
Hello, 

in documentation it https://docs.splunk.com/Documentation/Splunk/9.0.5/Indexer/Sitereplicationfactor it is written about explicit site_replication_factor, and nothing is added to https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md

so, how it suggested to set it up?

**Comment by logsecvuln** [comment]
adding ++ 

we have used the following configurations to push the explicit ssf and srf to Splunk, 
```
    - key: server
      value:
        directory: /opt/splunk/etc/system/local
        content:
          clustering:
            site_replication_factor:  origin:1,site1:1,site2:1,site3:1,site4:1,total:5
            site_search_factor: origin:1,site1:1,site2:1,site3:1,site4:1,total:5
            available_sites: site1,site2,site3,site4,site5,site6
            mutilsite: true
          imds:
            imds_version: v2
```

and as a result on the pod it has broken configuration as following, 
```
cat /opt/splunk/etc/system/local/server.conf

[general]
pass4SymmKey = somethiung

[sslConfig]
sslPassword = something

[clustering]
site_replication_factor = origin:1,site1:1,site2:1,site3:1,site4:1,total:5
site_search_factor = origin:1,site1:1,site2:1,site3:1,site4:1,total:5
available_sites = site1,site2,site3,site4,site5,site6
mutilsite = True
cluster_label = idxc_label
mode = manager
pass4SymmKey = alsosomething
search_factor = 3
site_replication_factor
site_search_factor
available_sites
mutilsite
...
```
