### ISSUE TITLE
Add TLS support of IDXC replication

### ISSUE THREAD

**Issue by Skypex** [splunk/splunk-ansible#779]
Hi,

currently it is not possible to setup an IDXC that uses TLS for replication.

You would setup an cluster like this:

```yaml
splunk:
    idxc:
        secret:
        pass4SymmKey:
        discoveryPass4SymmKey:
        label: "idxc_label"
        search_factor: 3
        replication_factor: 3
        replication_port: 9887
```

However, unfortunately there is no way to generate a `replication_port-ssl` stanza instead of an `replication_port` stanza.

Therefore I would kindly request to implement a switch that allows me to enable TLS on that port. It would be awesome if that works for multisite clusters as well.
