### ISSUE TITLE
Ansible breaks part of functionality on 9.2.x, if it is not license manager. 

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-ansible#821]
https://github.com/splunk/splunk-ansible/blob/9.2.1/roles/splunk_common/tasks/enable_forwarding.yml#L57 this breaks functionality of splunk deployment server. 

using defaults.yml file doesn't help. 
I suggest remove this block, or add new variable which will help to set it up.

**Comment by yaroslav-nakonechnikov** [comment]
atm workaround looks like:

```
- name: fix outputs.conf
  lineinfile:
    path: /opt/splunk/etc/system/local/outputs.conf
    regexp: '^(.*)index =(.*)$'
    line: 'index = True'
    backrefs: yes
  notify:
    - Restart the splunkd service
```
and setting `SPLUNK_ANSIBLE_POST_TASKS = "file:///mnt/path/to/post_tasks.yml"`
